# Generated by Django 6.1 on 2026-09-29 18:36

import baking.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='CustomOrderRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('fulfillment_type', models.CharField(choices=[('PICKUP', 'Local Pickup (Middelburg)'), ('DELIVERY', 'Middelburg Suburb Delivery')], default='PICKUP', max_length=10)),
                ('delivery_address', models.TextField(blank=True, default='', help_text='Street & Suburb in Middelburg (e.g., Aerorand, Kanonkop)')),
                ('event_date', models.DateField(validators=[baking.models.min_24h_lead_time])),
                ('servings_required', models.PositiveIntegerField(default=12)),
                ('flavor_preference', models.CharField(blank=True, default='', max_length=200)),
                ('dietary_requirements', models.CharField(blank=True, default='', help_text='e.g., Eggless, Nut-free, Gluten-free', max_length=200)),
                ('design_instructions', models.TextField(help_text='Describe theme, colors, or tier details')),
                ('reference_image', models.ImageField(blank=True, null=True, upload_to=baking.models.reference_image_path)),
                ('quoted_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('QUOTED', 'Quoted - Awaiting Payment'), ('DEPOSIT_PAID', 'Deposit Paid'), ('IN_PREPARATION', 'In Preparation'), ('READY', 'Ready for Pickup / Delivery'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='BakeryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='Set 0.00 for custom quoted items', max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='catalog/')),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='baking.category')),
            ],
        ),
    ]
