# Generated by Django 5.2 on 2026-10-07 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('subtitle', models.CharField(blank=True, default='', max_length=255)),
                ('image_url', models.URLField(help_text='Direct photo or Unsplash image URL', max_length=500)),
                ('button_text', models.CharField(default='Order Custom Cake', max_length=50)),
                ('button_link', models.CharField(default='/custom-order/', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
